builds/miatoll.json
changelogs/miatoll/ProjectElixir_1.8_miatoll-12.1-20220619-0853-OFFICIAL.txt

Signed-off-by: Abhishek001konni <Abhishek001konni@gmail.com>

miatoll: elixir 1.8

---

builds/spes.json
changelogs/spes/ProjectElixir_1.8_spes-12.1-20220619-1452-OFFICIAL.zip.txt

Signed-off-by: buglessx <fauzan@nusantararom.org>

spes: Project Elixir 1.8 Update

---

builds/crownlte.json
builds/star2lte.json
builds/starlte.json
changelogs/crownlte/ProjectElixir_1.8_crownlte-12.1-20220625-1436-OFFICIAL.zip.txt
changelogs/star2lte/ProjectElixir_1.8_star2lte-12.1-20220625-1617-OFFICIAL.zip.txt
changelogs/starlte/ProjectElixir_1.8_starlte-12.1-20220626-0509-OFFICIAL.zip.txt

Signed-off-by: pkttung <hubercraigf47455@gamil.com>

starlte/star2lte/crownlte: 1.8 Update

---

builds/sweet.json
changelogs/sweet/ProjectElixir_1.9_sweet-12.1-20220708-2130-OFFICIAL.zip.txt

sweet: Project Elixir 1.9 Update

---

builds/spes.json
changelogs/spes/ProjectElixir_1.9_spes-12.1-20220715-1458-OFFICIAL.zip.txt

Co-authored-by: buglessx <fauzan@nusantararom.org>
Signed-off-by: imannig <zahranansaria@gmail.com>

spes: Elixir 1.9

---

builds/RMX2170.json
changelogs/RMX2170/ProjectElixir_1.9_RMX2170-12.1-20220716-0908-OFFICIAL.zip.txt

Signed-off-by: Mayur <ultramayur123@gmail.com>

RMX2170: v1.9 update

---

builds/RMX1971.json
changelogs/RMX1971/ProjectElixir_1.9_RMX1971-12.1-20220721-0100-OFFICIAL.zip.txt

Merge the PR for RMX1971: Elixir v1.9

RMX1971: Elixir v1.9

---

builds/RMX2061.json
changelogs/RMX2061/ProjectElixir_1.8_RMX2061-12.1-20220613-0845-OFFICIAL.zip.txt
changelogs/RMX2061/ProjectElixir_1.9_RMX2061-12.1-20220723-0546-OFFICIAL.zip.txt

Signed-off-by: CxDxVER <starkinternational888@gmail.com>

RMX2061: Update 23/07/2022

---

builds/veux.json
changelogs/veux/ProjectElixir_2.0_veux-12.1-20220813-1612-OFFICIAL.zip.txt

Signed-off-by: JaswalAshish48 <jaswalashish48@gmail.com>

veux: V2.0 Update

---

builds/sweet.json
changelogs/sweet/ProjectElixir_2.0_sweet-12.1-20220819-2334-OFFICIAL.zip.txt

sweet: Project Elixir 2.0 Update

---

builds/juice.json
changelogs/ProjectElixir_2.0_chime-12.1-20220823-0917-OFFICIAL.zip.txt

Signed-off-by: imannig <zahranansaria@gmail.com>

chime: Elixir 2.0

---

builds/vince.json
changelogs/vince/ProjectElixir_2.0_vince-12.1-20220823-1141-OFFICIAL.zip.txt

Change-Id: I4eaaa163c398778a1deb7138f9f1baa151eea8b2
Signed-off-by: PrajjuS <theprajjus@gmail.com>

Elixir: vince 2.0 update

---

builds/instantnoodlep.json
changelogs/instantnoodlep/ProjectElixir_3.0_instantnoodlep-13.0-20220830-0907-BETA-OFFICIAL.zip.txt

Signed-off-by: dark-free <emchaouki@gmail.com>

Instantnoodlep: Elixir v3.0 | August Update | Android 13

---

builds/veux.json
changelogs/veux/ProjectElixir_3.0_veux-13.0-20220831-0406-BETA-OFFICIAL.zip.txt

Signed-off-by: JaswalAshish48 <jaswalashish48@gmail.com>

veux: v3.0 Release

---

builds/RMX2170.json
changelogs/RMX2170/ProjectElixir_3.0_RMX2170-13.0-20220830-1637-BETA-OFFICIAL.zip.txt

Signed-off-by: Mayur <ultramayur123@gmail.com>

RMX2170: Elixir v3.0 | August Update | Android 13

---

builds/sweet.json
changelogs/sweet/ProjectElixir_3.0_sweet-13.0-20220905-1434-BETA-OFFICIAL.zip

sweet: Elixir v3.0 | August Update | Android 13

---

builds/RMX3360.json
changelogs/RMX3360/ProjectElixir_2.1_RMX3360-12.1-20220907-0233-OFFICIAL.zip.txt

Signed-off-by: itsXRP <itsxrproms@gmail.com>

Elixir 2.1 EOL Update

---

builds/lemonades.json
changelogs/lemonades/ProjectElixir_3.0_lemonades-13.0-20220906-1330-BETA-OFFICIAL.zip.txt

new file:   builds/lemonades.json
new file:   changelogs/lemonades/ProjectElixir_3.0_lemonades-13.0-20220906-1330-BETA-OFFICIAL.zip.txt

lemonades: Elixir v3.0 | August Update | Android 13

---

builds/veux.json
changelogs/veux/ProjectElixir_2.1_veux-12.1-20220909-0641-OFFICIAL.zip.txt

Signed-off-by: JaswalAshish48 <jaswalashish48@gmail.com>

veux: v2.1 | EOL

---

builds/sweet.json
changelogs/sweet/ProjectElixir_2.1_sweet-12.1-20220909-1416-OFFICIAL.zip.txt

sweet: Project Elixir 2.1 Update

---

builds/vince.json
changelogs/vince/ProjectElixir_3.0_vince-13.0-20220911-0604-BETA-OFFICIAL.zip.txt

Change-Id: I98764de94cbd7d0c542ee715740059370215b41c
Signed-off-by: PrajjuS <theprajjus@gmail.com>

Elixir: vince 3.0 Initial BETA release

---

builds/RMX1971.json
changelogs/RMX1971/ProjectElixir_3.1_RMX1971-13.0-20220922-0604-BETA-OFFICIAL.zip.txt

Merge the PR for RMX1971: Release Elixir 3.1

RMX1971: Release Elixir 3.1

---

builds/RMX2061.json
changelogs/RMX2061/ProjectElixir_3.1_RMX2061-13.0-20220925-2000-BETA-OFFICIAL.zip.txt

Signed-off-by: CxDxVER <starkinternational888@gmail.com>

RMX2061: `Elixir v3.1`  |  `August Update`  |  `Android 13`

---

builds/vince.json
changelogs/vince/ProjectElixir_3.1_vince-13.0-20220926-1527-BETA-OFFICIAL.zip.txt

Change-Id: Ifed32f7337afae5e18a20125b85acead0611de61
Signed-off-by: PrajjuS <theprajjus@gmail.com>

Elixir: vince 3.1 update

---

builds/lavender.json
changelogs/ProjectElixir_3.1_lavender-13.0-20220927-0115-BETA-OFFICIAL.zip.txt

Signed-off-by: OmarAlCoptan <omarcoptan9@gmail.com>

lavender: update to 3.1

---

builds/chime.json
changelogs/chime/ProjectElixir_3.1_chime-13.0-20220927-1452-BETA-OFFICIAL.zip.txt

Signed-off-by: imannig <zahranansaria@gmail.com>

chime: Elixir v3.1

---

README.md
builds/x3.json
changelogs/x3/ProjectElixir_3.1_x3-13.0-20220929-0013-BETA-OFFICIAL.zip.txt

Signed-off-by: “Patriot-06” <mbmc172@gmail.com>

x3: Initial Project Elixir 3.1 Update

---

builds/RMX3360.json
changelogs/RMX3360/ProjectElixir_3.1_RMX3360-13.0-20221007-0818-BETA-OFFICIAL.zip.txt

Signed-off-by: itsxrp <itsxrproms@gmail.com>

RMX3360: Elixir v1.3

---

builds/miatoll.json
changelogs/miatoll/ProjectElixir_3.2_miatoll-13.0-20221015-0620-BETA-OFFICIAL.zip.txt

Signed-off-by: Abhishek001konni <Abhishek001konni@gmail.com>

miatoll: ELixir 3.2

---

changelogs/instantnoodlep/ProjectElixir_3.2_instantnoodlep-13.0-20221014-2134-BETA-OFFICIAL.zip.txt

Signed-off-by: dark-free <emchaouki@gmail.com>

instantnoodlep: Elixir 3.2 Release

---

builds/denniz.json
changelogs/denniz/ProjectElixir_3.2_denniz-13.0-20221014-1830-BETA-OFFICIAL.zip.txt

Change-Id: Idd010e1961bcb60140dd7c46ba489b154d7e3f35

denniz: Initial official release

---

builds/beryllium.json
changelogs/beryllium/ProjectElixir_3.2_beryllium-13.0-20221016-1906-BETA-OFFICIAL.zip.txt

Merge PR for beryllium: Release Elixir 3.2

beryllium: Release Elixir 3.2

---

README.md
builds/spaced.json
changelogs/spaced/ProjectElixir_3.2_spaced-13.0-20221019-1846-BETA-OFFICIAL.txt

Signed-off-by: rk134 <spaced@rk134.cf>

Elixir: RMX3151/RMX3286/spaced: Initialize v3.2!

---

builds/miatoll.json
changelogs/miatoll/ProjectElixir_3.3_miatoll-13.0-20221120-1149-OFFICIAL.zip.txt

Signed-off-by: Abhishek001konni <Abhishek001konni@gmail.com>

miatoll: Elixir v3.3

---

builds/sweet.json
changelogs/sweet/ProjectElixir_3.3_sweet-13.0-20221125-1414-OFFICIAL.zip.txt

sweet: Elixir v.3.3

---

builds/vince.json
changelogs/vince/ProjectElixir_3.3_vince-13.0-20221127-0639-OFFICIAL.zip.txt

Change-Id: I40ba29196b0d4234bc6d2ba6925008853e5c28eb
Signed-off-by: PrajjuS <theprajjus@gmail.com>

Elixir: vince 3.3 update

---

changelogs/RMX1971/ProjectElixir_3.5_RMX1971-13.0-20230112-0619-OFFICIAL.zip.txt

Kindly merge PR for updated changelog

RMX1971: Update Elixir 3.5 Changelog

---

builds/veux.json
changelogs/veux/ProjectElixir_3.5_veux-13.0-20230122-1433-OFFICIAL.zip.txt

Signed-off-by: JaswalAshish <jaswalashish48@gmail.com>

veux: Project-Elixir v3.5 Update

---

builds/X01BD.json
changelogs/X01BD/ProjectElixir_3.6_X01BD-13.0-20230303-0649-OFFICIAL.zip.txt

new file:   builds/X01BD.json
new file:   changelogs/X01BD/ProjectElixir_3.6_X01BD-13.0-20230303-0649-OFFICIAL.zip.txt

X01BD: Elixir v3.6 | February Update | Android 13

---

builds/taimen.json
builds/walleye.json

* Thanks for the elixir team for giving me a place, it's really unfortunate lately I've been a little busy with real life which makes me not have enough time to maintain the device tree that I manage. Once again, thank you and sorry if there is something that is not pleasing

Drop walleye/taimen

---

builds/taimen.json
builds/walleye.json
changelogs/taimen/ProjectElixir_3.11_taimen-13.0-20230819-0547-OFFICIAL.zip.txt
changelogs/walleye/ProjectElixir_3.11_walleye-13.0-20230819-0630-OFFICIAL.zip.txt

* walleye/taimen back to the land

wahoo: v3.11 | August Release | 2023

---

README.md
builds/devon.json
builds/hawao.json
builds/rhode.json
changelogs/devon/ProjectElixir_3.11_devon-13.0-20230820-0559-OFFICIAL.zip.txt
changelogs/hawao/ProjectElixir_3.11_hawao-13.0-20230820-0648-OFFICIAL.zip.txt
changelogs/rhode/ProjectElixir_3.11_rhode-13.0-20230820-0735-OFFICIAL.zip.txt

Add:
Moto G32 (devon)
Moto G42 (hawao)
Moto G52 (rhode)

Initial OTA for Motorola SM6225 Devices

---

builds/fog.json
changelogs/fog/ProjectElixir_3.11_fog-13.0-20230824-0341-OFFICIAL.zip.txt

fog: Initial official release

---

README.md
builds/haydn.json
changelogs/haydn/ProjectElixir_4.0_haydn-14.0-20240107-0634-OFFICIAL.txt

And update Maintainer name as well

Update: Haydn to 4.0
